"""MultiAction support

Revision ID: 102ddd686fcf
Revises: b4b4ed3ccf8d
Create Date: 2017-10-11 13:31:39.698960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102ddd686fcf'
down_revision = 'b4b4ed3ccf8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_json', sa.LargeBinary(), nullable=False),
    sa.Column('x_sha256', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('multi_action_string', sa.String(), nullable=False),
    sa.Column('multi_signature', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['member.id'], name=op.f('fk_multi_action_author_id_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multi_action')),
    sa.UniqueConstraint('x_sha256', name=op.f('uq_multi_action_x_sha256'))
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multi_action_id', sa.Integer(), nullable=True))
        batch_op.alter_column('signature',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_action_multi_action_id_multi_action'), 'multi_action', ['multi_action_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_action_multi_action_id_multi_action'), type_='foreignkey')
        batch_op.alter_column('signature',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('multi_action_id')

    op.drop_table('multi_action')
    # ### end Alembic commands ###
