"""Members can be updated

Revision ID: 28174fb4a2c6
Revises: 102ddd686fcf
Create Date: 2017-10-11 13:35:25.574287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28174fb4a2c6'
down_revision = '102ddd686fcf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('member', schema=None) as batch_op:
        mrc = batch_op.add_column(sa.Column('most_recent', sa.Boolean(), nullable=False, default = 1))

        batch_op.drop_constraint('uq_member_address', type_='unique')
        batch_op.drop_constraint('uq_member_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_member_name', ['name'])
        batch_op.create_unique_constraint('uq_member_address', ['address'])
        batch_op.drop_column('most_recent')

    # ### end Alembic commands ###
