"""Support for GPG keys

Revision ID: bcd18782dfa0
Revises: 28174fb4a2c6
Create Date: 2017-10-11 14:00:36.890137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd18782dfa0'
down_revision = '28174fb4a2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pgp_pubkey', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('pgp_pubkey')

    # ### end Alembic commands ###
